# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0002_auto_20161128_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование услуги')),
                ('label', models.PositiveSmallIntegerField(blank=True, max_length=3)),
            ],
        ),
    ]
