# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='label',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
