# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0004_auto_20161128_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=180, upload_to='uploads/%Y/%m/%d', verbose_name='Изображение галереи')),
                ('preview', models.FileField(blank=True, max_length=180, upload_to='')),
                ('file_preview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinika.Gallery')),
            ],
        ),
    ]
