# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0006_gallery_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(blank=True, max_length=512, verbose_name='Название новости')),
                ('news_data_day', models.PositiveSmallIntegerField(verbose_name='День выхода новости')),
                ('news_data_month', models.CharField(blank=True, max_length=20, verbose_name='Месяц выхода новости')),
                ('description_news', models.TextField(blank=True, max_length=512, verbose_name='Описание новости')),
                ('img_news', models.FileField(blank=True, max_length=180, upload_to='uploads/%Y/%m/%d', verbose_name='Изображение новости')),
            ],
        ),
    ]
