# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0010_auto_20161129_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='label',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
