# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0011_auto_20161129_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
