# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinika', '0012_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
