# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Электронная почта')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/avatar', verbose_name='Аватар')),
                ('avatar_icon', models.ImageField(blank=True, upload_to='user/avatar/icon')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('middlename', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('show_date_of_birth', models.BooleanField(default=True, verbose_name='Показывать д.р.')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('oklad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_low', models.NullBooleanField()),
                ('is_middle', models.NullBooleanField()),
                ('is_top', models.NullBooleanField()),
                ('is_emaigenerated', models.NullBooleanField(default=False)),
                ('date_post', models.DateField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Доп. почта')),
                ('extuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('extuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ext_phone_number',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('group', models.ManyToManyField(related_name='roles', to='auth.Group')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='extuser',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='extuser.Role'),
        ),
        migrations.AddField(
            model_name='extuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
